### ISSUE TITLE
Obj2: MAXFLOW

### ISSUE THREAD

**Issue by KFCDeveloper** [PredWanTE/DOTE#3]
Thank you for sharing your great work! Your wonderful work inspires me a lot. I can understand obj1, but I have some questions about obj2 in `dote.py`

1. Why add 0.1 to the predicted value in https://github.com/PredWanTE/DOTE/blob/43e628bd457e31958eba4f696e3de869d3e7789e/dote.py#L147
2. Why need alpha in https://github.com/PredWanTE/DOTE/blob/43e628bd457e31958eba4f696e3de869d3e7789e/dote.py#L149
3. Due to the questions above, I didn't understand why max_mcf is the value of MAXFLOW in https://github.com/PredWanTE/DOTE/blob/43e628bd457e31958eba4f696e3de869d3e7789e/dote.py#L154
4. And the loss is either 0 or 1 in https://github.com/PredWanTE/DOTE/blob/43e628bd457e31958eba4f696e3de869d3e7789e/dote.py#L156. Are there any special considerations?

**Comment by PredWanTE** [comment]
Hi, sorry for the late response.
1. To make these values non-negative.
2. This is the normalization factor Gamma which is mentioned in the paper.
3. For each commodity (source-destination pair), the amount of traffic that can be sent is the minimum between its allocation and its demand. MAXFLOW is the sum of these values.
4. 'loss_val' contains the actual (normalized) value of the loss. ('loss' is only used for updating the model (direction)).
